### ISSUE TITLE
Alan hesaplar

### ISSUE THREAD

**Issue by mustafaergan** [mustafaergan/Java-23-SE#1]
Üçgen, Daire ve Çokgen diye 3 sınıf olusturacaksiniz. 3'unde alan hesaplama, çevre hesaplama fonksiyonları olacak. İşlem sınıfı üzerinden bu foksiyonlara veri gönderilecek ve hesap sonuçları burada yazılacak

**Comment by hacidoganilbars** [comment]
[hdilbarsOdevCevreAlan.txt](https://github.com/mustafaergan/Java-23-SE/files/1116612/hdilbarsOdevCevreAlan.txt)
