### ISSUE TITLE
Dosya işlemi

### ISSUE THREAD

**Issue by mustafaergan** [mustafaergan/Java-23-SE#11]
Java ile önce kisiler diye bir dosya olusturulacak ardından bilgiler diye bir file oluşturup içine kendi bilgilerinizi yazaksiniz. Ardından farklı bir class bu bilgileri okuyup ekrana basacaksınız

**Comment by hacidoganilbars** [comment]
https://github.com/hacidoganilbars/Calismalarim/tree/master/ilbarsCalismalar/src/com/ilbars/hacidogan/odevdosyaokumayazma
