### ISSUE TITLE
Matematik

### ISSUE THREAD

**Issue by mustafaergan** [mustafaergan/Java-23-SE#2]
Hipotenüs hesabı yapılacak bir fonksiyon içerisinde.

**Comment by Esrayilmaz** [comment]
[Esra Yılmaz.txt](https://github.com/mustafaergan/Java-23-SE/files/1117417/Esra.Yilmaz.txt)

**Comment by oguzcansenel** [comment]
[Buyrun Hocam.txt](https://github.com/mustafaergan/Java-23-SE/files/1117419/Buyrun.Hocam.txt)

**Comment by hfatihsevim** [comment]
[hipotenüs.txt](https://github.com/mustafaergan/Java-23-SE/files/1117451/hipotenus.txt)

**Comment by hacidoganilbars** [comment]
[hdilbarsHipotenus.txt](https://github.com/mustafaergan/Java-23-SE/files/1117470/hdilbarsHipotenus.txt)

**Comment by hakancey** [comment]
[hipotenusHesaplama(HakanCeylan).txt](https://github.com/mustafaergan/Java-23-SE/files/1117670/hipotenusHesaplama.HakanCeylan.txt)

**Comment by rnustafa1** [comment]
[Mustafa(hipotenus).txt](https://github.com/mustafaergan/Java-23-SE/files/1127870/Mustafa.hipotenus.txt)
