### ISSUE TITLE
Baklava Dilimi

### ISSUE THREAD

**Issue by mustafaergan** [mustafaergan/Java-23-SE#4]
https://ckaynak.com/wp-content/uploads/2015/05/c-programlama-dili-baklava-dilimi-yapma.png

Şekilde ki gibi for'lar baklava dilimi oluşturulacaktır.

**Comment by DevelopAndGame** [comment]
[Deltoid.txt](https://github.com/mustafaergan/Java-23-SE/files/1125849/Deltoid.txt)

-Batuhan Harun Demirci

**Comment by hacidoganilbars** [comment]
[hdilbarsTersDikUcgen.txt](https://github.com/mustafaergan/Java-23-SE/files/1126223/hdilbarsTersDikUcgen.txt)

**Comment by hacidoganilbars** [comment]
[hdilbarsBaklavaDilimi.txt](https://github.com/mustafaergan/Java-23-SE/files/1126228/hdilbarsBaklavaDilimi.txt)

**Comment by hacidoganilbars** [comment]
[hdilbarsBaklavaDilimi.txt](https://github.com/mustafaergan/Java-23-SE/files/1126327/hdilbarsBaklavaDilimi.txt)

**Comment by hfatihsevim** [comment]
[baklava.txt](https://github.com/mustafaergan/Java-23-SE/files/1126597/baklava.txt)

**Comment by hakancey** [comment]
[BaklavaDilimi.txt](https://github.com/mustafaergan/Java-23-SE/files/1131767/BaklavaDilimi.txt)

**Comment by rnustafa1** [comment]
[Mustafa(Baklava).txt](https://github.com/mustafaergan/Java-23-SE/files/1132880/Mustafa.Baklava.txt)
