### ISSUE TITLE
Ters Dik Üçgen

### ISSUE THREAD

**Issue by mustafaergan** [mustafaergan/Java-23-SE#5]
Ters Dik üçgen yapılacak for ile ve ekrana bastırılacak.

**Comment by DevelopAndGame** [comment]
[DikUcgen.txt](https://github.com/mustafaergan/Java-23-SE/files/1125839/DikUcgen.txt)

-Batuhan Harun Demirci

**Comment by hacidoganilbars** [comment]
[hdilbarsTersDikUcgen.txt](https://github.com/mustafaergan/Java-23-SE/files/1126086/hdilbarsTersDikUcgen.txt)

**Comment by hacidoganilbars** [comment]
[hdilbarsTersDikUcgen.txt](https://github.com/mustafaergan/Java-23-SE/files/1126294/hdilbarsTersDikUcgen.txt)

**Comment by hacidoganilbars** [comment]
[hdilbarsTersDikUcgen.txt](https://github.com/mustafaergan/Java-23-SE/files/1126301/hdilbarsTersDikUcgen.txt)

**Comment by hakancey** [comment]
[TersDikUcgen.txt](https://github.com/mustafaergan/Java-23-SE/files/1131765/TersDikUcgen.txt)

**Comment by rnustafa1** [comment]
[Mustafa(TersDikUcgen).txt](https://github.com/mustafaergan/Java-23-SE/files/1132877/Mustafa.TersDikUcgen.txt)

**Comment by mustafaergan** [comment]
https://github.com/mustafaergan/merhabagit/tree/master/MerhabaGit
