### ISSUE TITLE
Matematik Soruları

### ISSUE THREAD

**Issue by mustafaergan** [mustafaergan/Java-23-SE#6]
http://www.ossmat.com/index.php/matematik-testleri/lise-1-testleri/temel-kavramlar/2970-temel-kavramlar-cozumlu-test-02.html

Matematik soruların program olarak yazılması. Burada mantığınıza en uygun gelen çözüm ile method yapmanızı istiyorum. 

Örnek 1 soru:

public class SoruBir {

	public int minBasamak(int a, int b) {
              /*soruda a için 4 basamak b için 3 basamak diyordu bu 4 ve 3 verdiğimde kaç basamak 
                 olduğunu vermektedir */
		int h = a - a % 1000;
		int m = b - b % 100;
		int sonuc = (h * m);
		int sayac = 0;
		while (sonuc > 0) {
			sayac++;
			sonuc /= 10;
		}

		return sayac;

	}

}

**Comment by hacidoganilbars** [comment]
https://github.com/hacidoganilbars/Calismalarim/commit/25ce91d4fbd924ed45f25574d44e22b4cf802cc6

**Comment by hacidoganilbars** [comment]
https://github.com/hacidoganilbars/Calismalarim/tree/master/ilbarsCalismalar

**Comment by hakancey** [comment]
https://github.com/hakancey/vektorelOdevler/tree/master/MatematikSorulari
