### ISSUE TITLE
Koleksiyonlarda LIFO FIFO

### ISSUE THREAD

**Issue by mustafaergan** [mustafaergan/Java-23-SE#7]
koleksiyonlarda lifo fifo örnekleri araştırıp bir tane örnek yapılacak.(Array ile yapılmayacak)

**Comment by hacidoganilbars** [comment]
https://github.com/hacidoganilbars/Calismalarim/tree/master/ilbarsCalismalar/src/ilbars/haci/dogan/odev_f%C4%B0fo_lifo

**Comment by hakancey** [comment]
https://github.com/hakancey/vektorelOdevler/tree/master/LifoFifo

**Comment by hacidoganilbars** [comment]
https://github.com/hacidoganilbars/Calismalarim/tree/master/ilbarsCalismalar/src/ilbars/haci/dogan/lifo_fifo
