### ISSUE TITLE
SQL Quiz

### ISSUE THREAD

**Issue by mustafaergan** [mustafaergan/Java-23-SE#8]
https://www.w3schools.com/sql/sql_quiz.asp burada %50 başarı yapmanızı bekliyorum.

**Comment by hacidoganilbars** [comment]
![odev](https://user-images.githubusercontent.com/29503674/28504262-969aebf4-701c-11e7-8df3-010ffb5038ad.PNG)

**Comment by hakancey** [comment]
![sqlquiz](https://user-images.githubusercontent.com/29770923/28737223-2759f77a-73f6-11e7-8570-c66317a443a5.JPG)
