### ISSUE TITLE
JDBC

### ISSUE THREAD

**Issue by mustafaergan** [mustafaergan/Java-23-SE#9]
Sizin oluşturmuş olduğunuz bir tabloda(pk ve en az 3 alanı olacak) java jdbc ile select, insert, update ve delete işlemlerinin yapılması gerekmektedir.

**Comment by hacidoganilbars** [comment]
https://github.com/hacidoganilbars/Calismalarim/tree/master/JDBC/src/ilbars/haci/dogan/jdbcOdev

**Comment by hakancey** [comment]
https://github.com/hakancey/vektorelOdevler/tree/master/JDBC
